### ISSUE TITLE
[BUG] Tapping on Samsung phones act as panning. 

### ISSUE THREAD

**Issue by ZahraVe** [bluefireteam/photo_view#454] opened 2021-08-03 12:58 UTC
**Describe the bug**

Having issue with single tap and also zoom in zoom out with double tap 

**Snippet**

```
PhotoViewGallery.builder(
                  itemCount: widget.currentPath.length,
                  builder: (BuildContext context, int index) {
                    return PhotoViewGalleryPageOptions(
                      imageProvider: AssetImage(widget.currentPath[index].path),
                      initialScale: PhotoViewComputedScale.covered,
                      minScale: PhotoViewComputedScale.contained,
                      maxScale: PhotoViewComputedScale.covered * 3,
                    );
                  },
                  enableRotation: true,
                  scrollPhysics: const BouncingScrollPhysics(),
                  pageController: _pageController,
                  loadingBuilder:
                      (BuildContext context, ImageChunkEvent event) {
                    return Center(child: CircularProgressIndicator());
                  },
                  onPageChanged: (int index) {
                    setState(() {
                      _currentIndex = index;
                    });
                  },
                  // backgroundDecoration:
                  //     BoxDecoration(color: kScreenBackgroundColor),
                  // scrollDirection: Axis.vertical,
                ),
```
**Which versions of Flutter/Photo View, and which browser / OS are affected by this issue? Did this work in previous versions of Photo View?**

photo_view: ^0.12.0

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.2.3 20D91 darwin-arm, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 4.1)
[✓] Connected device (1 available)

**Comment by sergiyvergun** [comment] 2021-10-04 07:39
Have the same issue only on Samsung S10, it works well on Xiaomi and iPhone.

Touch is recognized as slide.

**Comment by clragon** [comment] 2022-02-15 14:03
Duplicate of #216

**Closed** 2022-07-13 16:37 UTC
Labels: bug
