### ISSUE TITLE
Click event response is too slow

### ISSUE THREAD

**Issue by luckmlc** [bluefireteam/photo_view#521] opened 2022-08-04 10:58 UTC
Click event response After almost 200ms

How solve it?

use demo code，add GestureDetector onTap event code：
```
        GestureDetector(
              onTap: (){
                print('click test');
              },
              child: PhotoViewGallery.builder(
                scrollPhysics: const BouncingScrollPhysics(),
                builder: _buildItem,
                itemCount: widget.galleryItems.length,
                loadingBuilder: widget.loadingBuilder,
                backgroundDecoration: widget.backgroundDecoration,
                pageController: widget.pageController,
                onPageChanged: onPageChanged,
                scrollDirection: widget.scrollDirection,
              ),
            )
```

**Comment by renancaraujo** [comment] 2022-08-04 11:30
Dupe of #283

**Closed by renancaraujo** 2022-08-04 11:30 UTC
Labels: bug
