### ISSUE TITLE
Changes on flutter 2.5 affects `photo_view` library and prevents compilation.

### ISSUE THREAD

**Issue by rishad2m8** [bluefireteam/photo_view#470] opened 2021-09-26 04:16 UTC
When changing SDK version on pubspec.yaml to `">=2.7.0 <3.0.0"` from `">=2.12.0 <3.0.0"`, causes compilation failure with following message. 
`src/core/photo_view_gesture_detector.dart:106:29: Error: The argument type 'PointerEvent' can't be assigned to the parameter type 'PointerDownEvent'`. This is because there is a change in `addAllowedPointer` overriding from `ScaleGestureRecognizer` class.  
Reference: [GestureRecognizer cleanup](https://flutter.dev/docs/release/breaking-changes/gesture-recognizer-add-allowed-pointer)

**To Reproduce**
Change`sdk` version on pubspec.yaml to `">=2.7.0 <3.0.0"` and compile.

Flutter version: 2.5
Photo View version: 0.12.0

**Comment by Kaffeetasse** [comment] 2021-09-27 06:24
@rishad2m8 please search for existing Issues before opening a new one, here you can read more about that #459 

And I have seen the MR was merged so we should have an update soon.

**Comment by renancaraujo** [comment] 2021-09-27 12:11
Not exactly like #459 since it was fixed on 0.12.0.
 @rishad2m8 can you confirm this is reproduced on ` 0.12.0` ?

**Closed** 2021-10-04 09:26 UTC
Labels: bug, awaiting-further-comments
